#!/usr/bin/env node

var fs = require('fs')
var Handlebars = require('handlebars')
var files = ['PROJECTS', 'BADGES', 'HEADER', 'FOOTER']
var source = fs.readFileSync('../docs/templates/README.md.hbs').toString()
function getPartials(){
    files.forEach((file)=>{
        Handlebars.registerPartial(
            file,
            fs.readFileSync(`../docs/templates/${file}.md.hbs`).toString()
        )
    })
}
getPartials()
var template = Handlebars.compile(source);

var pkgs = ['cli', 'cli-runner', 'framework', 'framework-base', 'testing', 'testing-base']

var data = {
    pkg: require('../package.json'),
    pkgs: pkgs.map((pkg)=>{
        return require(`../packages/${pkg.replace("-", "/packages/")}/package.json`)
    })
}

var result = template(data);
// console.log(result);
fs.writeFileSync("../README.md", result);